Use node interface pointers in the TransformListener class
ros2/geometry2 pull request #100
Opened 2019-04-05 05:14 UTC by lbegani

In the TransformListener class, use node interfaces instead of using the node directly so that the code works with either rclcpp::Node or rclcpp_lifecycle::LifecycleNode. Retain the existing node-based interface for backwards compatibility.
This change fixes the issue reported here - https://github.com/ros2/geometry2/issues/94

2019-04-05 05:15 UTC, lbegani commented
@tfoote @mjeronimo - Kindly review.

2019-04-09 16:02 UTC, mjeronimo commented
@lbegani Looks good to me. 

@tfoote - One unfortunate consequence of ROS2's use of the interface pointers is that there is code duplication across the various classes that use these interfaces. For example, when creating a subscription, the topics interface itself isn't enough; there are templates on top of this required to get a memory strategy, etc. See: 
- TransformListener::create_subscription (this PR)
- Node::create_subscription
- LifecycleNode::create_subscription
- _Any other class that receives a topics interface and creates a subscription with it_

Perhaps these templates could be factored out somehow so that they could be used by any class that uses the topics interface (likewise with other interfaces that require addition "glue" templates).

2019-04-13 00:51 UTC, wjwwood commented
> Perhaps these templates could be factored out somehow so that they could be used by any class that uses the topics interface (likewise with other interfaces that require addition "glue" templates).

I'm working on something like this for another feature, see:

- https://github.com/ros2/rclcpp/blob/36ca81381355247ac03c3b2f0bd787422655a91e/rclcpp/include/rclcpp/node_interfaces/get_node_parameters_interface.hpp#L135-L157

And it being used:

- https://github.com/ros2/rclcpp/blob/36ca81381355247ac03c3b2f0bd787422655a91e/rclcpp/include/rclcpp/unused_parameters_checker.hpp#L44-L48

As a result, the `UnusedParametersChecker` class can take any struct or class that has the appropriate method to get the required interface (in this case the `NodeParameterInterface`.

I think a similar pattern could be provided for each node interface, and used in cases like this to decouple these classes from `rclcpp::Node` without having to have too much boilerplate.

2019-04-15 16:37 UTC, mjeronimo commented
@tfoote @lbegani  How about we get this one integrated and then create another PR for the factoring-out work?

2019-05-02 05:37 UTC, Karsten1987 requested changes
There are a couple of changes I'd like to have changed. Passing the shared pointer by value and re-using the `rclcpp::create_subscription` free function.

I am not sure about the priority of this package, but having these changes in for the dashing API freeze would be a great thing.

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/include/tf2_ros/transform_listener.h
> +  TransformListener(tf2::BufferCore & buffer, rclcpp::Node::SharedPtr nh, bool spin_thread = true);
this might be up for discussion, but I advocate for removing this constructor completely and thus force the usage of the node interfaces.

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/src/transform_listener.cpp
> +  return rclcpp::create_subscription<MessageT, CallbackT, Alloc, CallbackMessageT, SubscriptionT>(
why not calling this function directly?

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/include/tf2_ros/transform_listener.h
> +    const rclcpp::node_interfaces::NodeBaseInterface::SharedPtr & node_base,
don't pass a shared pointer by reference.

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/include/tf2_ros/transform_listener.h
> +  template<
this signature should not be necessary. Including [this](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/create_subscription.hpp) header file should be enough

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/src/transform_listener.cpp
> +  const rclcpp::node_interfaces::NodeBaseInterface::SharedPtr & node_base,
don't pass a shared pointer by reference

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/src/transform_listener.cpp
> +template<
same comment as before.

2019-05-02 05:37 UTC, Karsten1987 commented on tf2_ros/src/transform_listener.cpp
> +  for (unsigned int i = 0; i < msg_in.transforms.size(); i++) {
nitpick:  `for (auto i = 0u; ..)`

2019-05-08 17:29 UTC, Karsten1987 commented
in order to push this forward into dashing API freeze, I've opened #108 which is based on top of this PR. It's up for review

2019-05-10 01:01 UTC, tfoote commented
Replaced by #108

2019-05-10 01:01 UTC, closed without merging