Make sure that TransformListener's node gets a unique name
ros2/geometry2 pull request #129
Opened 2019-07-18 20:50 UTC by rotu

Fixes #124

2019-08-12 20:06 UTC, gonzodepedro requested changes
Pls, address comment.

2019-08-12 20:06 UTC, gonzodepedro commented on tf2_ros/src/transform_listener.cpp
> -void TransformListener::subscription_callback(const tf2_msgs::msg::TFMessage::SharedPtr msg, bool is_static)
Pls, remove new line on PR

2019-08-12 20:17 UTC, rotu commented on tf2_ros/src/transform_listener.cpp
> -void TransformListener::subscription_callback(const tf2_msgs::msg::TFMessage::SharedPtr msg, bool is_static)
Oops. Thanks

2019-08-13 14:47 UTC, gonzodepedro commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7871)](http://ci.ros2.org/job/ci_linux/7871/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3930)](http://ci.ros2.org/job/ci_linux-aarch64/3930/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6422)](http://ci.ros2.org/job/ci_osx/6422/)
* Windows [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7729)](https://ci.ros2.org/job/ci_windows/7729/)

* Unstable due to  unrelated errors

2019-08-13 14:48 UTC, gonzodepedro approved these changes
LGTM!

2019-08-13 18:10 UTC, merged