Overwrite TimeCacheInterface type with a current input
ros2/geometry2 pull request #151
Opened 2019-08-20 02:38 UTC by vinnamkim

Target to #150 

Signed-off-by: vinnamkim <vinnam.kim@gmail.com>

2019-08-27 00:56 UTC, tfoote requested changes
I think that it makes sense to support changing from one type of cache to the other based on newly published data. Just like we support reparenting. 

This looks reasonable, however this implementation is going to leak memory every time the type changes because the TimeCache objects are never deallocated before the new ones are allocated.

2019-09-11 07:55 UTC, vinnamkim commented
@tfoote I guess the old ones are shared pointers. If the new ones replace the old ones, It automatically will be deallocated.

2019-10-10 01:42 UTC, jacobperron commented
I think @vinnamkim is correct. Since the TimeCache objects are stored as shared pointers, they should be deallocated when the smart pointers are overridden with new objects in `allocateFrame`. I'll trigger CI for this and dependent packages, as it LGTM.

Testing packages that depend on tf2:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8323)](http://ci.ros2.org/job/ci_linux/8323/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4265)](http://ci.ros2.org/job/ci_linux-aarch64/4265/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6786)](http://ci.ros2.org/job/ci_osx/6786/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8223)](http://ci.ros2.org/job/ci_windows/8223/)

2019-10-19 00:25 UTC, tfoote approved these changes

2019-10-19 00:27 UTC, merged