Split tf2_ros in tf2_ros and tf2_ros_py
ros2/geometry2 pull request #210
Opened 2019-12-20 21:39 UTC by ahcorde

Following this issue  https://github.com/ros2/geometry2/issues/169 I splitted `tf2_ros` in 2 packages:

 - tf2_ros
 - tf2_ros_py

2020-01-13 14:14 UTC, clalancette requested changes
This generally looks good to me, but I'll request that we do unrelated cleanup in separate PRs.  That way this PR is just code motion, no changes at all.

2020-01-13 14:14 UTC, clalancette commented on tf2_ros/include/tf2_ros/message_filter.h
> +    add(MEvent(message, t));
This seems to be an unrelated change; can you split this out separately?

2020-01-13 14:14 UTC, clalancette commented on tf2_ros_py/package.xml
> +  <!-- <test_depend>rostest</test_depend> -->
I think we can just remove these at this point.  `xmlrpcpp` will never be a thing in ROS 2, the testing infrastructure is different (rostest goes away), and we'll reintroduce rosgraph if we need it.

2020-01-13 14:14 UTC, clalancette commented on tf2_ros_py/test/test_buffer_client.py
> +            'foo', 'bar', rclpy.time.Time().to_msg(), rclpy.duration.Duration(seconds=5.0))
Why is this change (and the similar ones below) needed in this port, but not in the original?

2020-01-17 13:10 UTC, clalancette requested changes
A bunch of changes in here.  The biggest one is switching tf2_ros_py to a pure Python package.

2020-01-17 13:10 UTC, clalancette commented on tf2_ros/package.xml
>    <depend>tf2_py</depend>
GitHub UI won't let me leave comments above this line, but this whole package.xml needs to be cleaned up.

1.  Now that we have no python things in here, the only "buildtool_depend" we need is `ament_cmake`.
1.  There is no direct dependency in this repository on `std_msgs`, so it should be removed.
1.  We may as well make `geometry_msgs` a regular `<depend>`, like the rest of the dependencies.
1.  This package no longer has a dependency on tf2_py.
1.  This package no longer needs pytest as a `test_depend`

Similar cleanups should probably be done in the CMakeLists.txt

2020-01-17 13:10 UTC, clalancette commented on tf2_ros_py/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
Is there any reason we can't make this a pure python package (no CMakeLists.txt at all)?  I think that would be more pythonic.

2020-01-17 13:10 UTC, clalancette commented on tf2_ros_py/package.xml
> +  <depend>tf2_ros</depend>
For a python package, there are really no `<build_depend>`, so just make all of these `<exec_depend>`

2020-01-17 13:10 UTC, clalancette commented on tf2_ros_py/package.xml
> +  <buildtool_depend>python_cmake_module</buildtool_depend>
If we end up making this a pure Python package, these will go away.

2020-01-17 13:10 UTC, clalancette commented on tf2_ros_py/test/test_buffer_client.py
> +            'foo', 'bar', rclpy.time.Time().to_msg(), rclpy.duration.Duration(seconds=5.0))
This comment is still open (and there are a couple more instances of it below).

2020-06-09 14:45 UTC, clalancette commented
All right, I reworked the tests here to succeed, and I've converted this to a pure Python package.  I'm going to do a self-review and run CI, but @ahcorde it would be good if you could take a look here.

2020-06-09 14:49 UTC, clalancette commented on tf2_ros_py/test/test_buffer_client.py
> +            'foo', 'bar', rclpy.time.Time().to_msg(), rclpy.duration.Duration(seconds=5.0))
That's just the way it works now.  The original didn't work.  Resolving this conversation.

2020-06-09 15:00 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11068)](http://ci.ros2.org/job/ci_linux/11068/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6381)](http://ci.ros2.org/job/ci_linux-aarch64/6381/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9013)](http://ci.ros2.org/job/ci_osx/9013/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10982)](http://ci.ros2.org/job/ci_windows/10982/)

2020-06-10 13:08 UTC, clalancette approved these changes
I'm going to approve this now, but this could use another look since I did some non-trivial changes here.

2020-06-11 16:04 UTC, ahcorde reviewed
LGTM, thank you @clalancette to take over this PR

2020-06-11 16:04 UTC, ahcorde commented on tf2_ros_py/tf2_ros/buffer_client.py
>          :param target_frame: Name of the frame to transform into.
:type *: is not defined as well as :rtype: . Should we open a ticket?

2020-06-11 18:06 UTC, clalancette commented on tf2_ros_py/tf2_ros/buffer_client.py
>          :param target_frame: Name of the frame to transform into.
Yeah, good call.  I'll open an issue to follow-up and add those annotations.

2020-06-11 18:51 UTC, clalancette commented
All right, CI was green, added a note to the release page.  Merging in, thanks for the review.

2020-06-11 18:52 UTC, merged