Style cleanup on tf2_py.cpp
ros2/geometry2 pull request #222
Opened 2020-01-22 10:39 UTC by ahcorde

https://github.com/ros2/geometry2/issues/168

2020-01-22 13:09 UTC, clalancette approved these changes
One thing to note: in the past we had been avoiding these kinds of cleanups in https://github.com/ros2/geometry2 in the hope that we could share code with https://github.com/ros/geometry2 .  I think these two forks have diverged enough that that is no longer a viable option, so I'm approving.  But before merging please get confirmation from @tfoote that this is OK.

2020-01-24 00:26 UTC, tfoote requested changes
I think we've diverged enough to let this cleanup happen. 

I had a few notes about the license headers though.

2020-01-24 00:26 UTC, tfoote commented on tf2_py/test/test_buffer_core.py
> +# Licensed under the Apache License, Version 2.0 (the "License");
This is changing the license and the year. That doesn't look right.

2020-01-24 00:26 UTC, tfoote commented on tf2_py/test/__init__.py
> +# Licensed under the Apache License, Version 2.0 (the "License");
This is changing the license not linting it.

2020-01-24 00:26 UTC, tfoote commented on tf2_py/src/tf2_py.cpp
> +// Copyright 2020 Open Source Robotics Foundation, Inc.
This should have the BSD license to match the origin's license.

2020-01-24 00:26 UTC, tfoote commented on tf2_py/src/python_compat.h
> +// Copyright 2020 Open Source Robotics Foundation, Inc.
This should have the BSD header as it's from the legacy code base.

2020-01-24 00:26 UTC, tfoote commented on tf2_py/tf2_py/__init__.py
> +# Software License Agreement (BSD License 2.0)
What's the BSD License 2.0? This is the 3-Clause BSD if you want a proper name.

2020-01-24 09:04 UTC, ahcorde commented
@tfoote  I have reviewed again the licenses

I have seen that the licenses are The 3-Clause BSD License. But the only bsd license accepted is BSD 2.0 according with the code ament_copyright https://github.com/ament/ament_lint/blob/master/ament_copyright/ament_copyright/licenses.py#L41

2020-01-28 04:25 UTC, tfoote commented
I don't know where @clalancette got that copy of the license for https://github.com/ament/ament_lint/commit/767257ff141d7957f3c8c7b92106aced95794537 

There's no such things at "Version 2" listed at https://spdx.org/licenses/BSD-3-Clause.html or https://opensource.org/licenses/BSD-3-Clause or as is in the code. That looks like an accidental copy and paste misstep. 

In general though the linter needs to be able to accept any valid license. We can do minor whitespace updates if necessary but otherwise we cannot change the verbiage in the license on anything except what we've originally written. We talked about this a while ago and knew that the linters were too strict for applying to imported code. But we chose just not to turn them on instead of making them much more generic for expediency. If we want to turn them on for legacy code they will need to be updated to be more flexible.

2020-01-28 13:04 UTC, clalancette commented
> I don't know where @clalancette got that copy of the license for [ament/ament_lint@767257f](https://github.com/ament/ament_lint/commit/767257ff141d7957f3c8c7b92106aced95794537)
> 
> There's no such things at "Version 2" listed at https://spdx.org/licenses/BSD-3-Clause.html or https://opensource.org/licenses/BSD-3-Clause or as is in the code. That looks like an accidental copy and paste misstep.

Yeah, I'm honestly not sure where that came from now that I look at it.  https://github.com/ament/ament_lint/issues/109 addresses some of the same issue.

> In general though the linter needs to be able to accept any valid license. We can do minor whitespace updates if necessary but otherwise we cannot change the verbiage in the license on anything except what we've originally written. We talked about this a while ago and knew that the linters were too strict for applying to imported code.

https://github.com/ament/ament_lint/issues/75 (somewhat).

> But we chose just not to turn them on instead of making them much more generic for expediency. If we want to turn them on for legacy code they will need to be updated to be more flexible.

For this PR, I'll suggest that we go back to the old copyright for now, and just disable the copyright check.  Once we figure out the ament_lint situation, we can come back and turn it on.

2020-01-30 08:20 UTC, ahcorde commented
@clalancette, 

Excluded ament_copyright

should I include the license in the C++ code? beacuse cpplint is also failing because of the licence

2020-01-30 13:22 UTC, clalancette commented
> should I include the license in the C++ code? beacuse cpplint is also failing because of the licence

I would say let's turn off cpplint for now as well.  Once we resolve the situation in ament_lint, we can revisit this and reenable those.

2020-01-30 13:25 UTC, ahcorde commented
Excluded cpplint too, should I run the CI?

2020-01-31 14:32 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9199)](http://ci.ros2.org/job/ci_linux/9199/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4896)](http://ci.ros2.org/job/ci_linux-aarch64/4896/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7502)](http://ci.ros2.org/job/ci_osx/7502/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9118)](http://ci.ros2.org/job/ci_windows/9118/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=5)](http://ci.ros2.org/job/ci_windows-container/5/)

2020-01-31 14:48 UTC, clalancette approved these changes

2020-02-12 14:51 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9308)](http://ci.ros2.org/job/ci_linux/9308/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5000)](http://ci.ros2.org/job/ci_linux-aarch64/5000/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7618)](http://ci.ros2.org/job/ci_osx/7618/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9234)](http://ci.ros2.org/job/ci_windows/9234/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=111)](http://ci.ros2.org/job/ci_windows-container/111/)

2020-02-17 15:33 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9371)](http://ci.ros2.org/job/ci_linux/9371/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5054)](http://ci.ros2.org/job/ci_linux-aarch64/5054/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7673)](http://ci.ros2.org/job/ci_osx/7673/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9280)](http://ci.ros2.org/job/ci_windows/9280/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=154)](http://ci.ros2.org/job/ci_windows-container/154/)

2020-02-18 07:54 UTC, merged

2020-02-21 17:20 UTC, dirk-thomas commented
The change broke all jobs running on Ubuntu Focal: http://build.ros2.org/view/Fci/

```
geometry2/tf2_py/src/tf2_py.cpp:1059:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t’ {aka ‘long int’} in initialization
 1059 | };
      | ^
```

@ahcorde Please fix asap.