Replace '/tf', '/tf_static' with 'tf' and 'tf_static to support node namespace
ros2/geometry2 pull request #326
Opened 2020-09-29 06:19 UTC by hyunseok-yang

Hi all,

Since several month ago, I'm researching multi-robot scenario based on ROS2 using node namespace to separate the group of topics for each robot. (Not ROS_DOMAIN_ID)

And I could easily separate by the namespace on other ROS2 nodes but '/tf' and '/tf_static'.
It always needs topic remapping like /tf:=tf  and /tf_static:=tf.

So, here is the idea and code suggestion.
Why don't we just use relative topic name for those??

I don't see the reason that we should use an absolute path for.

Could any guys let me know the history? if not I'd like suggest to change a absolute path to relative path for 'TF' :)

Signed-off-by: Hyunseok Yang <hyunseok7.yang@lge.com>

2020-10-05 02:04 UTC, hyunseok-yang commented
Anyone, let me know what happened on Jekins. 

It looks just system error....
[http://build.ros2.org/job/Rpr__geometry2__ubuntu_focal_amd64/131/testReport/](http://build.ros2.org/job/Rpr__geometry2__ubuntu_focal_amd64/131/testReport/)

2020-10-05 12:27 UTC, clalancette commented
> Anyone, let me know what happened on Jekins.

That was a temporary problem with pytest, which I believe should be resolved now.  I'll rekick the test.

2020-10-05 12:27 UTC, clalancette commented
@ros-pull-request-builder retest this please

2020-10-06 06:27 UTC, zikprid0 commented
I have same problems too. 
I also remapped "tf" for rviz2.
I think it is good idea.

2020-10-22 17:48 UTC, tfoote requested changes
The tf topics are specifically scoped to be absolute because they should not follow the majority of node namespace remappings.

The one case where they do generally need to be remapped is in the multi-robot use case which as you've pointed out has solutions. If we made this change, anybody who remapped a node name would then have to either remap the tf topics back out of the node's namespace or you could only have one namespace per robot. Namespaces are designed to be much lighter weight and you can setup small processing groups and launch them into subnamespaces to keep them isolated. But all the nodes generally need access to tf data and tf data is not subject to the namespace, it's related to the physical spaces of the robot.

Thus as you've identified in the physical case of multi robot use cases you need to start paying attention and isolating the tf topics. However those use cases are much more specialized and less common than the use of any namespaces on the whole system. Thus we require the multi-robot use case to incur the requirement of explicitly remapping the absolute topics versus requiring every node to pay attention to unremapping the tf topics when they get pushed down into a namespace.

2020-11-06 15:08 UTC, clalancette commented
Given @tfoote 's comments about this, I'm going to close this out.  But feel free to reopen or keep commenting if you think otherwise.

2020-11-06 15:08 UTC, closed without merging