Clarify the role of child_frame_id and header.frame_id in the documentation.
ros2/geometry2 pull request #345
Opened 2020-11-12 19:47 UTC by wecacuee

I think the description in `geometry_msgs/TransformStamped` is wrong with respect to the behaviour of sendTransform.

> This expresses a transform from coordinate frame header.frame_id to the coordinate frame child_frame_id

Source: http://docs.ros.org/en/api/geometry_msgs/html/msg/TransformStamped.html

However, `Broadcaster::sendTransform` adds a transform from `child_frame_id` to `header.frame_id`. 

What does a transform from `child_frame_id` to `header.frame_id` mean? It is better to be concrete than to be vague. Hence, the symbols included in the documentation. One can also refer to the tf/Overview wiki http://wiki.ros.org/tf/Overview/Transformations

2020-11-12 20:12 UTC, clalancette requested changes
While I'm all for improving the documentation, I think this is much harder to read in a standard text editor.  Can we get rid of the Tex(?) annotations and use either ascii or maybe utf-8 instead?

2020-11-12 21:21 UTC, wecacuee commented
Nice idea! Used utf-8 for the math.

2020-11-16 15:07 UTC, clalancette approved these changes
Works for me, thanks for the improvement.  I'll run CI on it just to ensure things are happy.

2020-11-16 15:08 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13063)](http://ci.ros2.org/job/ci_linux/13063/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8010)](http://ci.ros2.org/job/ci_linux-aarch64/8010/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10787)](http://ci.ros2.org/job/ci_osx/10787/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13044)](http://ci.ros2.org/job/ci_windows/13044/)

2020-11-16 19:06 UTC, merged