Fix linter errors
ros2/geometry2 pull request #385
Opened 2021-03-03 04:42 UTC by audrow

2021-03-03 04:49 UTC, audrow commented
Here is CI, which ran all CI up from `ament_uncrustify`, including the failing packages in this repo (see [here](https://ci.ros2.org/job/ci_linux/13782/)). 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13789)](http://ci.ros2.org/job/ci_linux/13789/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8657)](http://ci.ros2.org/job/ci_linux-aarch64/8657/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11498)](http://ci.ros2.org/job/ci_osx/11498/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13866)](http://ci.ros2.org/job/ci_windows/13866/)

2021-03-03 07:04 UTC, ahcorde requested changes
the job is failing https://build.ros2.org/job/Rpr__geometry2__ubuntu_focal_amd64/202/

2021-03-04 17:21 UTC, audrow commented
@ros-pull-request-builder retest please

2021-03-04 17:27 UTC, audrow commented
@ros-pull-request-builder retest this please

2021-03-04 17:49 UTC, clalancette commented on tf2_ros/include/tf2_ros/message_filter.h
> +    if (!in.empty() && (in[0] == '/')) {
@audrow So the issue seems to be that the linter in the PR job wants this to be the old code, that is `in [0] == '/'`.  Does the new linter want it to be without the space?

2021-03-04 21:03 UTC, clalancette commented
@ros-pull-request-builder retest this please

2021-03-04 21:59 UTC, clalancette approved these changes
This looks good to me.

Let's wait for the result of the Windows job (which I just kicked again) before merging this.

2021-03-05 13:41 UTC, clalancette commented
The failures on Windows are well-known, so going ahead and merging this one.

2021-03-05 13:41 UTC, merged