Fix tf_echo does not work with ros-args (#407)
ros2/geometry2 pull request #408
Opened 2021-04-30 08:56 UTC by PGotzmann

Enables the usage of `--ros-args`  by removing them before parsing the other command line parameters.
Fixes #407

2021-04-30 11:03 UTC, ahcorde approved these changes

2021-04-30 12:35 UTC, clalancette requested changes
Two relatively minor changes, then I think this will be good to have CI run on it.

2021-04-30 12:35 UTC, clalancette commented on tf2_ros/src/tf2_echo.cpp
> +  if (args.size() < 3 || args.size() > 4) {
I'll suggest refactoring this a slightly different way (since we are in here making edits anyway).  In particular, I think it would be nicer to have the following:

```
if (args.size() == 3) {
  rate_hz = 1.0;
} else if (args.size() == 4) {
  rate_hz = std::stof(args[3]);
} else {
   printf(USAGE_MESSAGE);
   return -1;
}
```

And then continue on with the rest of the code.  What do you think about that?

2021-04-30 12:35 UTC, clalancette commented on tf2_ros/src/tf2_echo.cpp
> +  std::string target_frameid = std::string(args[2]);
```suggestion
  std::string source_frameid = args[1];
  std::string target_frameid = args[2];
```

2021-05-03 08:14 UTC, PGotzmann commented on tf2_ros/src/tf2_echo.cpp
> +  if (args.size() < 3 || args.size() > 4) {
Sounds reasonable to me. This is certainly the more strait forward way here.
I will update the PRs accordingly.

2021-05-03 09:00 UTC, PGotzmann commented
> Two relatively minor changes, then I think this will be good to have CI run on it.

Updated the PR according to your feedback.
Let me know if you are happy with that now. If so i'll update the foxy backport too.

2021-05-03 12:58 UTC, clalancette approved these changes
I made a few changes here to make argument parsing more robust.  This looks good to me now; thanks for the contribution!  I'll run CI on it next.

2021-05-03 12:59 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14539)](http://ci.ros2.org/job/ci_linux/14539/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9295)](http://ci.ros2.org/job/ci_linux-aarch64/9295/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12204)](http://ci.ros2.org/job/ci_osx/12204/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14645)](http://ci.ros2.org/job/ci_windows/14645/)

2021-05-03 15:00 UTC, merged

2021-05-03 15:21 UTC, clalancette commented
@Mergifyio backport galactic foxy