Reenable stamped eigen tests
ros2/geometry2 pull request #429
Opened 2021-05-29 14:39 UTC by gleichdick

Github didn't let me reopen #424, so here we go...

TL;DR Reenable some tf2_eigen tests which should also work on MSVC. The rest stays disabled.

2021-05-31 07:24 UTC, ahcorde requested changes
Style looks weird

2021-05-31 07:24 UTC, ahcorde commented on tf2_eigen/test/tf2_eigen-test.cpp
> +        5)), "test");
```suggestion
  const tf2::Stamped<Eigen::Vector3d> v(Eigen::Vector3d(1, 2, 3), tf2::TimePoint(
      std::chrono::seconds(5)), "test");
```

2021-05-31 07:24 UTC, ahcorde commented on tf2_eigen/test/tf2_eigen-test.cpp
> +        42)), "test_frame");
```suggestion
  const Eigen::Affine3d v_nonstamped(Eigen::Translation3d(1, 2, 3) * Eigen::AngleAxis<double>(
      1, Eigen::Vector3d::UnitX()));
  const tf2::Stamped<Eigen::Affine3d> v(v_nonstamped, tf2::TimePoint(
      std::chrono::seconds(42)), "test_frame");
```

2021-05-31 13:29 UTC, gleichdick commented
Retriggering CI

2021-05-31 18:22 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14705)](http://ci.ros2.org/job/ci_linux/14705/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9457)](http://ci.ros2.org/job/ci_linux-aarch64/9457/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12370)](http://ci.ros2.org/job/ci_osx/12370/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14849)](http://ci.ros2.org/job/ci_windows/14849/)

2021-06-01 07:28 UTC, ahcorde approved these changes
@clalancette do you mind to review it ?

2021-06-01 13:03 UTC, clalancette approved these changes

2021-06-01 13:04 UTC, merged