Hide canTransform console output
ros2/geometry2 pull request #472
Opened 2021-10-24 23:31 UTC by smnogar

I got sick of seeing `canTransform` spam the terminal with the message:

```
Warning: Invalid frame ID "robot/base_link" passed to canTransform argument source_frame - frame does not exist
at line 156 in /Users/steve/Documents/ros2_galactic/src/ros2/geometry2/tf2/src/buffer_core.cpp
```

Obviously its desired behavior that canTransform should be checking for frames that don't exist yet. I'm sure there are cleaner ways of doing this but here is my method. Relevant issue is https://github.com/ros2/geometry2/issues/405.

2021-10-25 01:46 UTC, aprotyas requested changes
No comments on whether this change is desirable, but leaving some inline comments to address.

2021-10-25 01:46 UTC, aprotyas commented on tf2/src/buffer_core.cpp
> +#include <string.h>
string.h is a C library, so it's better to use:
```suggestion
#include <cstring>
```

2021-10-25 01:46 UTC, aprotyas commented on tf2/src/buffer_core.cpp
> +  if (id == 0 && strstr(function_name_arg, "canTransform") == NULL) {
Nitpick
```suggestion
  if (id == 0 && std::strstr(function_name_arg, "canTransform") == nullptr) {
```

2021-10-25 01:49 UTC, aprotyas commented on tf2/src/buffer_core.cpp
> +#include <string.h>
You'd also want to place the header inclusion after line 32 to maintain alphabetical ordering of the headers.

2021-10-25 12:25 UTC, clalancette commented
I don't think we should be hiding this completely.  It's a useful indicator of whether things eventually get published that will complete the tf tree.  Further, if we remove this now after so many years of having it in, people will wonder what happened when they upgraded.

That said, I do think that this should throttled.  That is, we should only print it for a particular transform once every X number of seconds (we can argue about X, I think it should be ~5 seconds).

2021-10-25 17:45 UTC, smnogar commented
@clalancette Looking over the ros1 version of geometry2, it doesn't output anything when canTransform fails to find a frame. This was introduced in ros2. 

I agree that functions like lookupTransform and other related functions should still output when a requested frame doesn't exist, but in the case of canTransform, a user may be waiting for a frame to exist before performing some action. Prior to this fix, every check of canTransform that returns false generates console error warnings.

2021-10-25 18:26 UTC, clalancette commented
@emersonknapp Can you provide a bit more context on the intent of #187 ?  Having this console spam hasn't been super popular (see this PR, https://github.com/ros2/geometry2/pull/395, #405, #396, and #358, at least), but I also don't want to remove it if it has a valid use.

2021-10-25 18:31 UTC, emersonknapp commented
I think the main point was that the existing error messages were not informative. I agree it's too spammy - maybe a "throttle" or "once on state change" would be more useful - but I don't really have any strong feelings any particular way.

2021-10-25 18:34 UTC, aprotyas commented
> "once on state change"

+1

2021-11-04 06:36 UTC, aprotyas commented
@smnogar I don't think this is the way to proceed with this issue since it would suppress output even when it is both valid and warranted.

Since everyone is on the same page about the output being spammy, the design should follow either of the general ideas provided by @emersonknapp. If you want to try implementing that, go for it - but that should probably be submitted as a new PR.

2021-11-08 18:20 UTC, smnogar commented
I disagree that the output is warranted, since this kind of output was never present in ros1. I'll close this, and if someone else wants to implement the solution @emersonknapp suggested they can make a new PR.

2021-11-08 18:20 UTC, closed without merging