Replace deprecated spin_until_future_complete
ros2/geometry2 pull request #512
Opened 2022-03-31 15:26 UTC by hliberacki

Replace deprecated spin_until_future_complete with spin_until_complete

Signed-off-by: Hubert Liberacki <hliberacki@gmail.com>

2022-03-31 15:26 UTC, hliberacki commented
Due to change in RCLCPP - https://github.com/ros2/rclcpp/pull/1874 Pull request

2022-04-01 16:24 UTC, fujitatomoya requested changes
re-formatting changes should be avoided.

2022-04-01 16:24 UTC, fujitatomoya commented on tf2_tools/tf2_tools/view_frames.py
> +    parser.add_argument('-o', '--output', help='Output filename')
i think that we can keep this.

2022-04-01 16:24 UTC, fujitatomoya commented on tf2_tools/tf2_tools/view_frames.py
> +            'Result:' + str(result))
i think that we can keep this.

2022-04-01 16:24 UTC, fujitatomoya commented on tf2_tools/tf2_tools/view_frames.py
> +
i think that we can keep this.

2022-04-01 16:24 UTC, fujitatomoya commented on tf2_tools/tf2_tools/view_frames.py
> +
i think that we can keep this.

2022-04-01 16:24 UTC, fujitatomoya commented on tf2_tools/tf2_tools/view_frames.py
> +
i think that we can keep this.

2022-04-04 13:08 UTC, hliberacki commented
https://github.com/ros2/rclcpp/pull/1874#issuecomment-1086906375 Passing CI with all related PRs linked and build together.

2022-06-24 18:41 UTC, SteveMacenski approved these changes

2024-04-02 21:48 UTC, christophebedard commented
I've opened #667 to replace this PR.

2024-04-10 18:14 UTC, christophebedard commented
This can be closed, see https://github.com/ros2/geometry2/pull/667#issuecomment-2035715786

2024-04-10 18:22 UTC, closed without merging