Add orocos-kdl include directories to CMakeLists.txt
ros2/geometry2 pull request #551
Opened 2022-08-18 11:58 UTC by srmainwaring

This PR adds `${orocos_kdl_INCLUDE_DIRS}` to the target include directories for `tf2_geometry_msgs` and `tf2_kdl`.

### System

Mac Pro running macOS Monterey Version 12.5, Xcode 13.4.1

### Issue

The build of ros2 humble on macOS does not resolve the include directories for `orocos_kdl` unless they are explicitly added to the target include directories. `orocos-kdl` is installed with brew, details below:

```bash
brew info orocos-kdl        
==> orocos-kdl: stable 1.5.1 (bottled)
Orocos Kinematics and Dynamics C++ library
https://orocos.org/
/usr/local/Cellar/orocos-kdl/1.5.1 (106 files, 1MB) *
  Poured from bottle on 2022-08-18 at 12:27:46
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/orocos-kdl.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: cmake ✔
Required: eigen ✔
```

2022-08-18 12:02 UTC, clalancette requested changes
So the problem here is that we *explicitly* don't want to do this; it ends up putting hard-coded paths into the exported CMake files for downstream consumers.  This works fine if you are building from source, but when you are distributing binaries, those hard-coded paths are almost certainly wrong.

I think the right fix here would be to figure out why the target that https://github.com/ros2/orocos_kdl_vendor/blob/rolling/orocos_kdl_vendor/orocos_kdl_vendor-extras.cmake is providing isn't working properly.  That should fix the problem, and also not put hard-coded paths into the output.

2022-08-18 12:06 UTC, srmainwaring commented
Thanks for the quick feedback - I'll look into `orocos_kdl_vendor-extras.cmake` as suggested.

2022-08-18 12:06 UTC, closed without merging

2023-06-25 13:10 UTC, PhDittmann commented
For me, `orocos_kdl_vendor-extras.cmake` detects the orocos-kdl homebrew installation, as expected, but also does not provide the include directory.

It seems to be a bug in `$(brew --prefix orocos-kdl)/share/orocos_kdl/cmake/OrocosKDLTargets.cmake`, which is generated by CMake. As hotfix, after installing orocos-kdl via hombrew, add in `$(brew --prefix orocos-kdl)/share/orocos_kdl/cmake/OrocosKDLTargets.cmake` after `add_library(orocos-kdl SHARED IMPORTED)` (line 59)

```
set_target_properties(orocos-kdl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```

The origin of the bug is, that [orocos_kdl/src/CMakeLists.txt](https://github.com/orocos/orocos_kinematics_dynamics/tree/update_cmake/orocos_kdl/src) does not contain
```
TARGET_INCLUDE_DIRECTORIES(orocos-kdl PUBLIC
  "$<INSTALL_INTERFACE:include>")
```

It's fixed in [update_cmake](https://github.com/orocos/orocos_kinematics_dynamics/blob/update_cmake/orocos_kdl/src/CMakeLists.txt) branch (1st of April 2022), but not merged, yet.

2023-06-28 20:03 UTC, PhDittmann commented
Patch for orocos-kdl v1.5.1 was accepted. [#134944](https://github.com/Homebrew/homebrew-core/pull/134944) Try 

```console
brew update
brew reinstall orocos-kdl
```