Add do_transform_polygon_stamped
ros2/geometry2 pull request #582
Opened 2023-02-07 11:53 UTC by tonynajjar

https://github.com/ros2/geometry2/issues/581

This is an initial draft, please give feedback on the idea, thanks!

2023-03-17 17:22 UTC, clalancette requested changes
In short, this is completely new functionality so I'm happy to have it in.  There are two flake8 errors to be resolved, but once those are fixed we can run CI on it.

2023-03-17 17:22 UTC, clalancette commented on tf2_geometry_msgs/src/tf2_geometry_msgs/tf2_geometry_msgs.py
> +                               TransformStamped, Vector3Stamped)
flake8 suggests:

```suggestion
from geometry_msgs.msg import (Point, Point32, PointStamped, PolygonStamped, Pose,
                               PoseStamped, PoseWithCovarianceStamped,
                               TransformStamped, Vector3Stamped)
```

2023-03-17 17:22 UTC, clalancette commented on tf2_geometry_msgs/src/tf2_geometry_msgs/tf2_geometry_msgs.py
> +
Add an extra newline here:

```suggestion


```

2023-03-17 20:21 UTC, clalancette approved these changes

2023-03-17 20:22 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18254)](http://ci.ros2.org/job/ci_linux/18254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12790)](http://ci.ros2.org/job/ci_linux-aarch64/12790/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18929)](http://ci.ros2.org/job/ci_windows/18929/)

2023-03-18 12:46 UTC, merged

2023-03-21 14:00 UTC, tonynajjar commented
Would love to have it backported to Humble if possible

2023-03-21 15:58 UTC, clalancette commented
@Mergifyio backport humble