Destroy callback group before node
ros2/geometry2 pull request #595
Opened 2023-04-12 17:50 UTC by mjcarroll

The new executor implementation gives an exception if callback groups and nodes are destructed out of order.  

It is incorrect for callback groups to be held alive longer than their owning nodes, but we previous didn't warn about it.

2023-04-12 17:58 UTC, clalancette approved these changes
Yeah, this makes sense to me.  Will run CI on just this change next.

2023-04-12 17:59 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18526)](http://ci.ros2.org/job/ci_linux/18526/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13073)](http://ci.ros2.org/job/ci_linux-aarch64/13073/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19256)](http://ci.ros2.org/job/ci_windows/19256/)

2023-04-12 19:07 UTC, clalancette requested changes

2023-04-12 19:07 UTC, clalancette commented on tf2_ros/include/tf2_ros/transform_listener.h
> +
Uncrustify is not happy with this extra line.

```suggestion
```

2023-04-12 22:11 UTC, mjcarroll commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18531)](http://ci.ros2.org/job/ci_linux/18531/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13077)](http://ci.ros2.org/job/ci_linux-aarch64/13077/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19262)](http://ci.ros2.org/job/ci_windows/19262/)

2023-04-13 14:47 UTC, clalancette approved these changes

2023-04-13 14:47 UTC, merged