Enable StaticTransformBroadcaster in Intra-process enabled components
ros2/geometry2 pull request #607
Opened 2023-06-13 10:06 UTC by roncapat

Follow up of [this](https://github.com/ros2/geometry2/pull/572#issuecomment-1361192871) comment made by @FranzAlbers (and PR #572 in general).

FYI  @nachovizzo(https://github.com/PRBonn/kiss-icp/pull/171) and @fixit-davide.

2023-06-21 18:07 UTC, clalancette requested changes
Two small changes, then I'll run CI on it.

2023-06-21 18:07 UTC, clalancette commented on tf2_ros/include/tf2_ros/static_transform_broadcaster.h
> +        /tf topic, when the TransformListener is constructed using an existing
```suggestion
        /tf_static topic, when the TransformListener is constructed using an existing
```

2023-06-21 18:07 UTC, clalancette commented on tf2_ros/include/tf2_ros/static_transform_broadcaster.h
> +        /tf topic, when the TransformListener is constructed using an existing
```suggestion
        /tf_static topic, when the TransformListener is constructed using an existing
```

2023-06-22 14:12 UTC, roncapat commented
I also added a small test as I did for the TransformListener :)

2023-06-22 14:12 UTC, clalancette approved these changes
Looks good, thanks for the addition of the test!

2023-06-22 14:13 UTC, roncapat commented
@clalancette wait wait, I missed some fixes to the comments
sorry!

2023-06-22 14:29 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19013)](http://ci.ros2.org/job/ci_linux/19013/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13537)](http://ci.ros2.org/job/ci_linux-aarch64/13537/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19766)](http://ci.ros2.org/job/ci_windows/19766/)

2023-06-22 17:47 UTC, merged

2023-06-22 18:33 UTC, roncapat commented
Thanks a lot! Can we backport to iron and humble?

2023-06-23 08:19 UTC, ahcorde commented
https://github.com/Mergifyio backport iron humble