Add doTransform support for Point32, Polygon and PolygonStamped
ros2/geometry2 pull request #616
Opened 2023-08-16 14:34 UTC by doisyg

Point32 and PolygonStamped were in the python API but not the cpp one. Added them along with  Polygon

2023-08-16 15:10 UTC, ahcorde requested changes

2023-08-16 15:10 UTC, ahcorde commented on tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp
> + * \param t_out The transformed point, as a Point3 message.
```suggestion
 * \param t_in The point to transform, as a Point32 message.
 * \param t_out The transformed point, as a Point32 message.
```

2023-08-16 15:10 UTC, ahcorde commented on tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp
> +geometry_msgs::msg::Point32 & toMsg(const tf2::Vector3 & in, geometry_msgs::msg::Point32 & out)
using an argument and return for the same. Is there any reason to do so ?

2023-08-16 16:08 UTC, doisyg commented on tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp
> +geometry_msgs::msg::Point32 & toMsg(const tf2::Vector3 & in, geometry_msgs::msg::Point32 & out)
No idea, I just copied what was done for the `geometry_msgs::msg::Point` :
https://github.com/ros2/geometry2/blob/621be6be286a57360de18818744a17a3a61528f9/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp#L221-L233

2023-08-17 09:46 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19345)](http://ci.ros2.org/job/ci_linux/19345/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13872)](http://ci.ros2.org/job/ci_linux-aarch64/13872/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20066)](http://ci.ros2.org/job/ci_windows/20066/)

2023-08-17 11:58 UTC, merged

2023-08-17 12:01 UTC, ahcorde commented
https://github.com/Mergifyio backport iron rolling