Removing console_bridge
ros2/geometry2 pull request #655
Opened 2024-03-01 04:19 UTC by CursedRock17

This pull request directly addresses issue #570 which is meant to remove the `console_bridge` dependencies from tf2 and opt for a ROS 2 solution of logging. I went with the basic forms of `RCUTILS_LOG_WARN/ERROR` as it seems to be most sensible. Though, this could be swapped to `RCLCPP_LOG_*` or more advanced forms like `RCUTILS_LOG_WARN_NAMED` depending on the extent of the information we want the user to have.

2024-03-01 09:39 UTC, ahcorde requested changes
There are 3 new warnings, do you mind to fix them?

https://build.ros2.org/job/Rpr__geometry2__ubuntu_jammy_amd64/263/clang-tidy/new/

2024-03-01 12:14 UTC, CursedRock17 commented
Yup, they're all fixed now, it seems CI errors are now related to flake8 tests in other parts of the repository.

2024-03-01 13:23 UTC, ahcorde requested changes
warning are still there https://build.ros2.org/job/Rpr__geometry2__ubuntu_jammy_amd64/264/clang-tidy/new/

TF2Error is a enum of `std::uint8_t`
```cpp
enum class TF2Error : std::uint8_t
```

Take a look to my suggestion

2024-03-01 13:23 UTC, ahcorde commented on tf2/src/buffer_core.cpp
> +        RCUTILS_LOG_ERROR("Unknown error code: %d", retval);
```suggestion
        RCUTILS_LOG_ERROR("Unknown error code: %u", static_cast<std::uint8_t>(retval));
```

2024-03-04 09:05 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20406)](http://ci.ros2.org/job/ci_linux/20406/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14816)](http://ci.ros2.org/job/ci_linux-aarch64/14816/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21156)](http://ci.ros2.org/job/ci_windows/21156/)

2024-03-04 09:05 UTC, ahcorde approved these changes

2024-03-04 15:14 UTC, merged