Transform Data Callback Python
ros2/geometry2 pull request #664
Opened 2024-03-29 03:51 UTC by CursedRock17

This PR is meant to resolve #194 as of right now I'm working off of PR #215. We need to add a callback function, most likely `_wait_for_transform_async`, which returns the transform data similar to the C++ version returning a `TransformStampedFuture`.

2024-04-02 18:36 UTC, clalancette approved these changes
I think this is generally the correct thing to do here.  I have a mild concern that this will cause some downstream code to break, but looking through all of the code released into rolling, nothing seems to use this in particular.  I'm going to run CI on this, but @CursedRock17 can you please also open a PR to http://docs.ros.org/en/rolling/Releases/Release-Jazzy-Jalisco.html to add a note saying that we changed this?

2024-04-02 18:37 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20704)](http://ci.ros2.org/job/ci_linux/20704/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15018)](http://ci.ros2.org/job/ci_linux-aarch64/15018/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21393)](http://ci.ros2.org/job/ci_windows/21393/)

2024-04-02 19:00 UTC, clalancette requested changes

2024-04-02 19:00 UTC, clalancette commented on tf2_ros_py/tf2_ros/buffer.py
> +            fut.set_result(self.lookup_transform(target_frame, source_frame, time))
Oh, right.  This should probably be `self.lookup_transform_full_core`, to match the `can_transform_full_core` above.

2024-04-02 19:54 UTC, clalancette commented on tf2_ros_py/tf2_ros/buffer.py
> +            fut.set_result(self.lookup_transform_full_core(target_frame, source_frame, time))
I'm pretty sure this has a different API: https://github.com/ros2/geometry2/blob/4fd450d2f4f5c8157c80a9c283e1f50b65f3b400/tf2_ros_py/tf2_ros/buffer.py#L190

2024-04-03 20:29 UTC, clalancette approved these changes

2024-04-03 20:30 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20730)](http://ci.ros2.org/job/ci_linux/20730/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15035)](http://ci.ros2.org/job/ci_linux-aarch64/15035/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21411)](http://ci.ros2.org/job/ci_windows/21411/)

2024-04-04 01:50 UTC, CursedRock17 commented
The CI should still be fine, but I forgot to update the return value in the docs

2024-04-04 01:50 UTC, clalancette commented
I think this is good to go other than the addition to the release notes.  Once that PR is open, I'll go ahead and merge this.

2024-04-04 07:55 UTC, merged