Add cache_benchmark
ros2/geometry2 pull request #679
Opened 2024-05-14 01:09 UTC by EricCousineau-TRI

Towards #676

@clalancette Would you be OK reviewing this?

2024-05-14 08:41 UTC, ahcorde requested changes

2024-05-14 08:41 UTC, ahcorde commented on tf2/test/cache_benchmark.cpp
> +// Copyright 2024, Willow Garage, Inc. All rights reserved.
```suggestion
// Copyright 2024, Open Source Robotics Foundation, Inc.. All rights reserved.
```

2024-05-14 08:41 UTC, ahcorde commented on tf2/test/cache_benchmark.cpp
> +      return std::make_tuple(timestamp, step);
include `<tuple>`

2024-05-14 14:34 UTC, EricCousineau-TRI commented on tf2/test/cache_benchmark.cpp
> +// Copyright 2024, Willow Garage, Inc. All rights reserved.
Done c2dd515a

2024-05-14 14:34 UTC, EricCousineau-TRI commented on tf2/test/cache_benchmark.cpp
> +      return std::make_tuple(timestamp, step);
Done c2dd515a

2024-05-14 16:19 UTC, clalancette requested changes
One more minor change, then I'll run CI on it.

2024-05-14 16:19 UTC, clalancette commented on tf2/test/cache_benchmark.cpp
> +#include <tuple>
```suggestion
#include <chrono>
#include <tuple>
```

2024-05-14 16:51 UTC, EricCousineau-TRI commented
done, thanks!

2024-05-14 19:29 UTC, EricCousineau-TRI commented
is it possible to run this through full platform testing? (Linux, Mac, Win)

2024-05-14 19:35 UTC, clalancette commented
> is it possible to run this through full platform testing? (Linux, Mac, Win) for it to then merge?

We don't run CI on macOS, but yes, here is the rest of the CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21084)](http://ci.ros2.org/job/ci_linux/21084/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15387)](http://ci.ros2.org/job/ci_linux-aarch64/15387/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21801)](http://ci.ros2.org/job/ci_windows/21801/)

2024-05-15 07:54 UTC, ahcorde approved these changes

2024-05-15 12:19 UTC, clalancette approved these changes

2024-05-15 12:19 UTC, merged

2024-05-28 08:03 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy

2024-05-28 13:18 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron