Adding NodeInterfaces API Design
ros2/geometry2 pull request #714
Opened 2024-10-12 03:56 UTC by CursedRock17

Meant to resolve #698 this pull request deprecates and replaces all instances of `NodeT` within the `geometry2` repo with [`rclcpp::node_interfaces::NodeInterfaces`](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/node_interfaces/node_interfaces.hpp). This PR also replaces #661 to close #95.

While the key is to deprecate the old templated node methods there are some kinks, particularly in the [`StaticTransformBroadcaster`](https://github.com/ros2/geometry2/blob/6e5f0433119b19b71c57fab06906cdf92e8c49c8/tf2_ros/include/tf2_ros/static_transform_broadcaster.h#L84-#L98) and [`TransformBroadcaster`](https://github.com/ros2/geometry2/blob/6e5f0433119b19b71c57fab06906cdf92e8c49c8/tf2_ros/include/tf2_ros/transform_broadcaster.h#L84-#L99) classes in which a dereferenced node will prefer this templated version opposed to an implicit conversion. This is fine if we decide to keep the `NodeT` constructors in addition to the `NodeInterfaces` ones, but I feel that's pointless as we're trying to remove as template code here as we can.

2024-11-06 17:16 UTC, ahcorde requested changes
I can see many error in the job build https://build.ros2.org/job/Rpr__geometry2__ubuntu_noble_amd64/116/

Let me know when do you need a review.

2025-08-15 04:04 UTC, CursedRock17 commented
Evening @ahcorde, this pull request is now ready for review if you have the bandwidth. A couple things I'd like to stress:
  - To force the compiler to prefer the non-templated variants over the now deprecated constructors, my resolution was to check if the `NodeT` was actually a `shared_ptr`, then deference it. So I brought in [rcpputils](https://docs.ros.org/en/rolling/p/rcpputils/generated/structrcpputils_1_1is__pointer.html), is this ok?
  - I added `deprecated` forms of many tests to continously check the deprecated constructors, it adds a bunch of extra tests, but those can be removed in M-turtle.
  - There's now going to be an abundance of deprecation warnings, for many repositories, just [`TransformBroadcaster`](https://github.com/search?q=tf2_ros%3A%3ATransformBroadcaster&type=code) has 12K results alone. Is this something that needs to be announced in any capacity, or should I just fix the ["main" dependencies](https://index.ros.org/p/tf2_ros/#rolling-deps)?

2025-08-22 10:05 UTC, ahcorde requested changes

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/include/tf2_ros/buffer.hpp
> +  /** \brief  Constructor for a Buffer object
```suggestion
      NodeLoggingInterface, NodeServicesInterface>;

  /** \brief  Constructor for a Buffer object
```

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/include/tf2_ros/buffer.hpp
> +    std::enable_if_t<rcpputils::is_pointer<NodeT>::value, bool> = true>
include `<type_traits>`

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/include/tf2_ros/message_filter.hpp
>    template<typename TimeRepT = int64_t, typename TimeT = std::nano>
include `<cstdint>`

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/include/tf2_ros/static_transform_broadcaster.hpp
> +    std::enable_if_t<rcpputils::is_pointer<NodeT>::value, bool> = true>
include `<type_traits>`

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/include/tf2_ros/transform_listener.hpp
> +
remove this new line

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/src/buffer.cpp
> +        std::placeholders::_2), qos, nullptr);
include `<functional>`

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/test/message_filter_test.cpp
> +   }
```suggestion
  }
```

2025-08-22 10:05 UTC, ahcorde commented on tf2_ros/test/message_filter_test.cpp
>        std::chrono::microseconds(0));
include `<chrono>`

2025-08-22 16:29 UTC, CursedRock17 commented
Headers and Cleanup Changes Implemented.

2025-08-25 08:49 UTC, ahcorde commented
Pulls: ros2/geometry2#714
Gist: https://gist.githubusercontent.com/ahcorde/aeb266edba13e8d794f7b6a215113e94/raw/e8164211ede5998be08b658c6d7e5e6580094ef4/ros2.repos
BUILD args:  --packages-above-and-dependencies test_tf2 tf2_ros
TEST args:  --packages-above test_tf2 tf2_ros
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16788
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24696)](http://ci.ros2.org/job/ci_linux/24696/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18719)](http://ci.ros2.org/job/ci_linux-aarch64/18719/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4144)](http://ci.ros2.org/job/ci_linux-rhel/4144/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25214)](http://ci.ros2.org/job/ci_windows/25214/)

2025-08-25 11:05 UTC, ahcorde requested changes
Windows is not compiling https://ci.ros2.org/job/ci_windows/25214/console

2025-08-27 02:16 UTC, CursedRock17 commented
Whoops, forgot visibility headers! Those changes are in, along with some loose deprecation warnings that have been cleaned up.

2025-08-27 08:11 UTC, ahcorde commented
Pulls: ros2/geometry2#714
Gist: https://gist.githubusercontent.com/ahcorde/6d434e18a5e696d403b1985760f1128c/raw/e8164211ede5998be08b658c6d7e5e6580094ef4/ros2.repos
BUILD args:  --packages-above-and-dependencies test_tf2 tf2_ros
TEST args:  --packages-above test_tf2 tf2_ros
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16793
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=24701)](http://ci.ros2.org/job/ci_linux/24701/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=18726)](http://ci.ros2.org/job/ci_linux-aarch64/18726/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=4149)](http://ci.ros2.org/job/ci_linux-rhel/4149/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=25219)](http://ci.ros2.org/job/ci_windows/25219/)

2025-08-27 12:34 UTC, ahcorde approved these changes

2025-08-27 12:34 UTC, merged