tf2_echo: specifies quaternion order to be xyzw
ros2/geometry2 pull request #718
Opened 2024-10-25 11:50 UTC by abhishek47kashyap

Per #717

Targets `rolling` but can be backported to earlier distros that haven't reached EOL (`jazzy`, `iron`, `humble`) because the change is only a single `std::cout`.

2024-10-25 12:06 UTC, ahcorde requested changes
Thank you for the PR, there are some linter issues https://build.ros2.org/job/Rpr__geometry2__ubuntu_noble_amd64/118/

2024-10-25 12:28 UTC, abhishek47kashyap commented on tf2_ros/src/tf2_echo.cpp
> +        ", " << rotation.z << ", " << rotation.w << "]" << std::endl;
Diff `", " <<` is to comply with the linter.

2024-10-28 12:33 UTC, ahcorde commented
Pulls: ros2/geometry2#718
Gist: https://gist.githubusercontent.com/ahcorde/5dbc7df10f224c6b7d9e10b5d146297d/raw/f1e3b4899ff9cd9a9c8ca3def77f8de309555361/ros2.repos
BUILD args:   --packages-above-and-dependencies tf2_ros --packages-above-and-dependencies tf2_ros
TEST args:  --packages-above tf2_ros --packages-above tf2_ros
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14735
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22035)](http://ci.ros2.org/job/ci_linux/22035/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16292)](http://ci.ros2.org/job/ci_linux-aarch64/16292/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1553)](http://ci.ros2.org/job/ci_linux-rhel/1553/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22768)](http://ci.ros2.org/job/ci_windows/22768/)

2024-10-28 12:46 UTC, clalancette commented
> Targets `rolling` but can be backported to earlier distros that haven't reached EOL (`jazzy`, `iron`, `humble`) because the change is only a single `std::cout`.

While I'm on board with adding this to `rolling`, I'm hesitant to add it to the stable distributions.  That's because people could be running the existing binary and parsing the output, and this would break that use case.  So I'd say let's get this into Rolling for now, and leave it there.  If you disagree strongly, let me know and I can bring it up with the rest of the ROS PMC to get more input.

2024-10-28 21:01 UTC, merged