Adding StaticTransformListener in Python
ros2/geometry2 pull request #719
Opened 2024-10-26 03:33 UTC by CursedRock17

As per the title, this pull request is meant to compliment #673 and hopefully close #662 by adding the `StaticTransformListener` in Python.

2024-10-28 12:06 UTC, ahcorde requested changes
can you also add the test ?

2024-10-28 12:06 UTC, ahcorde commented on tf2_ros_py/tf2_ros/static_transform_listener.py
> +# Copyright (c) 2008, Willow Garage, Inc.
```suggestion
# Copyright (c) 2024, Open Source Robotics Foundation, Inc.
```

2024-10-28 12:06 UTC, ahcorde commented on tf2_ros_py/tf2_ros/static_transform_listener.py
> +# author: Wim Meeussen
remove or add yourself

2024-10-28 12:06 UTC, ahcorde commented on tf2_ros_py/tf2_ros/static_transform_listener.py
> +        :param node: The ROS2 node.
```suggestion
        :param node: The ROS 2 node.
```

2024-10-30 01:37 UTC, CursedRock17 commented
> can you also add the test ?

As in a whole new testing suite or another set of individualized tests? The `StaticTransformListener` should be applicable in `test_static_broadcaster_and_listener`, just a faster version of the `TransformListener`.

2024-10-31 09:01 UTC, ahcorde commented
> > can you also add the test ?
> 
> As in a whole new testing suite or another set of individualized tests? The `StaticTransformListener` should be applicable in `test_static_broadcaster_and_listener`, just a faster version of the `TransformListener`.

The mentioned PR adds some new tests to `test_transform_listener.cpp`, I would suggest to add something similar to `tf2_ros_py`

2024-11-06 17:14 UTC, ahcorde commented
Pulls: ros2/geometry2#719
Gist: https://gist.githubusercontent.com/ahcorde/8eca404e13a04ad871146a39db4cdcc2/raw/9d524ee1ccc2723415616719d3026e29857f0835/ros2.repos
BUILD args:   --packages-above-and-dependencies tf2_ros_py --packages-above-and-dependencies tf2_ros_py
TEST args:  --packages-above tf2_ros_py --packages-above tf2_ros_py
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14794
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22099)](http://ci.ros2.org/job/ci_linux/22099/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16355)](http://ci.ros2.org/job/ci_linux-aarch64/16355/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1619)](http://ci.ros2.org/job/ci_linux-rhel/1619/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22839)](http://ci.ros2.org/job/ci_windows/22839/)

2024-11-06 17:15 UTC, ahcorde approved these changes

2024-11-07 13:30 UTC, merged