Update message_filter.h
ros2/geometry2 pull request #91
Opened 2019-02-04 11:31 UTC by sagniknitr

The rclcpp::Time Clock "now" call seemed wrong. This is the correct way to do it seems.

2019-02-07 02:13 UTC, tfoote requested changes
Yes, using the static method is sub-optimal, it won't get . The correct solution is not to construct a new Clock object but call get_clock() on the member node_. Or the convenience method now() on the node which does that [under the hood](https://github.com/ros2/rclcpp/blob/0f9098e9b65169c9c4902a3b504733144f4bcab2/rclcpp/src/rclcpp/node.cpp#L237)

Constructing a Clock object but not attaching a time source to it is basically the same as the static method. I believe that API didn't exist when this was first implemented.

2019-02-12 06:48 UTC, sagniknitr commented
@tfoote  Thanks for the review. Sorry couldn't apply the changes earlier.

2019-02-15 00:54 UTC, tfoote commented
Thanks for the update @sagniknitr 

Triggering CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6200)](http://ci.ros2.org/job/ci_linux/6200/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2653)](http://ci.ros2.org/job/ci_linux-aarch64/2653/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5114)](http://ci.ros2.org/job/ci_osx/5114/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6054)](http://ci.ros2.org/job/ci_windows/6054/)

2019-02-15 00:54 UTC, tfoote approved these changes

2019-02-15 01:46 UTC, merged